### ISSUE TITLE
How Do I Make A New Page

### ISSUE THREAD

**Issue by JimTheMan** [greglobinski/gatsby-starter-hero-blog#53]
without getting errors???

**Comment by JimTheMan** [comment]
I found this (page)[https://dev.greglobinski.com/install-blog-starter/] and the section labeled "Pages". It is very brief, but it helped me a little. So, just make a new folder under `conent/meta/pages`?

Do I / should I ever need to edit the json files manually or are they just generated for me?

thanks

**Comment by mohsenkhanpour** [comment]
@JimTheMan Hey Jimmy, there is no `content/meta/pages` .
There is `content/meta/config.js` which holds the meta information of your project.
And there is `content/pages/[no--title]`.

In order to create a new page just create a folder with `no--title` (`no` being number, `--` being a separator, and `title` your desired title. Gatsby automatically generates your page for you, and `hero-starter` creates a link to that page in the menu.

Everything is clearly documented in [the page you mentioned](https://dev.greglobinski.com/install-blog-starter/), so please do your research.

**Comment by JimTheMan** [comment]
thanks. It's not very clear, but I figured it out.
